<?php

/**
 * @file
 * Allow users to create prebuilt lists for webforms using existing API
 */

/** 
 * Implements hook_menu()
 */
function prebuilt_lists_menu() {
	
	
  // Show existing prebuilt lists
  $items['admin/structure/prebuilt-lists'] = array(
    'title' => 'Prebuilt Lists',
    'description' => 'Show all existing Prebuilt Lists',
    'access arguments' => array('access administration pages'),
    'page callback' => prebuilt_lists_list,
    'file' => 'prebuilt_lists.admin.inc',
    'file path' => drupal_get_path('module', 'prebuilt_lists'),
  );
  
  // Create new list
  $items['admin/structure/prebuilt-lists/new'] = array(
    'title' => 'New List',
    'description' => 'Create a new list for use and reuse in Webforms',
    'page callback' => prebuilt_lists_new,
    'file' => 'prebuilt_lists.admin.inc',
    'file path' => drupal_get_path('module', 'prebuilt_lists'),
  );
  
  return $items;
}

//TODO: Create logic for inserting new lists into the database. Issue #3
//TODO: Implement hook_webform_select_options_info() Issue #4
//TODO: Allow editing of existing lists in the database. Issue #5
//TODO: Check for valid keys when inserting or updating. Autogenerate keys assuming input is only the Value. Issue #9

