<?php

/**
 * @file
 * Allow users to create prebuilt lists for webforms using existing API
 */

/** 
 * Implements hook_menu()
 */
function prebuilt_lists_menu() {
	
	
  // Show existing prebuilt lists
  $items['admin/structure/prebuilt-lists'] = array(
    'title' => t('Prebuilt Lists'),
    'description' => t('Show all existing Prebuilt Lists'),
    'access callback' => 'user access',
    'access arguments' => array('access administration pages'),
    'page callback' => 'prebuilt_lists_list',
    'file' => 'prebuilt_lists.admin.inc',
    'file path' => drupal_get_path('module', 'prebuilt_lists'),
  );
  
  // Create new list
  $items['admin/structure/prebuilt-lists/new'] = array(
    'title' => t('New List'),
    'description' => t('Create a new list for use and reuse in Webforms'),
    'page callback' => 'new_prebuilt_lists_page',
    'access callback' => 'user access',
    'access arguments' => array('create prebuilt lists'),
    'file' => 'prebuilt_lists.admin.inc',
    'file path' => drupal_get_path('module', 'prebuilt_lists'),
  );
  
  return $items;
};

/**
 * Implements hook_permission()
 */
 
function prebuilt_lists_permission() {
  return array(
    'view prebuilt lists' => array(
      'title' => t('View Prebuilt Lists'),
      'description' => t('Allows the user to view lists that have already been created'),
    ),
    'create prebuilt lists' => array(
      'title' => t('Create/Update Prebuilt Lists'),
      'description' => t('Allows the user to create new lists and update existing ones'),
    ),
  );
};

function prebuilt_lists_fetch($number = 10) {
  $result = db_query("SELECT * FROM {prebuilt_lists} ORDER BY list_id ASC", 0, $number);
  return $result;
};

//TODO: Create logic for inserting new lists into the database. Issue #3
//TODO: Implement hook_webform_select_options_info() Issue #4
//TODO: Allow editing of existing lists in the database. Issue #5
//TODO: Check for valid keys when inserting or updating. Autogenerate keys assuming input is only the Value. Issue #9