<?php

/**
 * Admin Pages for Prebuilt Lists, allows for showing all lists and creating new ones.
 */
 
/**
 * Menu callback for admin/structure/prebuilt-lists
 */

function prebuilt_lists_list() {
  //TODO: Query Database to select all in list table. Issue # 6
  //TODO: Add pagination for lots of lists. Issue #7
  return;
};

/**
 * Menu callback for admin/structure/prebuilt-lists/new
 */

function prebuilt_lists_new() {
  //TODO: Build forms for creating a new list. Issue #2
  return;
};
